bcgsc/physlr

physlr/physlr.py
Just did some small rearrangements of the code
=> reformatting of the code

data/Makefile, physlr/physlr.py
Updates:
Message passing function: determine_reachability_by_message_passing + ...
Removing branches of a tree based on size and messages: prune_branches_of_tree.
Determing and pruned maximum spanning tree: physlr_pruned_mst.
=> Pruned mst

data/Makefile, physlr/physlr.py
implement prunning inside physlr_mst
+ Makefile: physlr mst
+ argument for prunning
=> physlr_mst: integrate pruning

.pylintrc, physlr/physlr.py
using a combination of algorithms to perform the molecule separation
=> Extensive separation

data/Makefile, physlr/physlr.py
Code reformatting for the molecule stage:
- lesser lines of codes
- easy to add new strategies
Tested for .k3 and bi-connected. the results were totally identical
=> Reformat determine molecules

src/include/indexlr-minimize.h, src/include/indexlr-workers.h, src/physlr-indexlr.cc, src/vendor/ntHashIterator.h
Add indexlr strand update to physlr (which includes a deadlock fix). The code changes are simply the differences between ntJoin and physlr indexlr code.
=> Indexlr strand data update

.pylintrc, physlr/physlr.py
Pylint got updated recently. New checks came with the new updates and all our future CIs will break as a result.
Added exception to non top level import.
Changed all `exit` to `sys.exit`
=> Pylint errors

physlr/physlr.py
Removes singletons after molecule separation
=> determine_molecule: remove singletons afterward

.pylintrc, physlr/physlr.py
that `l` property was for troubleshooting by Shaun, so I factored out this troubleshooting part into another function.
note the previous push is not merged into master so there are some other difference between the codes. I'll wait until I merge the previous pull request and then I'll add reviewers [update]: previous updates are merged to master and here as well.
=> Code cleaning

data/Makefile
The Ensembl genome has more intuitive chromosome names.
2L 2R 3L 3R 4 X Y MT
=> data: Download the fly genome from Ensembl

data/Makefile, data/plothistogram.rmd, physlr/physlr.py
This PR contains the initial steps to building a repetitive Bloom filter using kmers determined by ntHits with a repeat threshold cutoff calculated using the output of ntCard.
=> ntHits and ntCard integration

src/Makefile
Forgot to add dependency in the previous #103
=> Makefile: add makebf check dependency to check

src/Makefile
=> Makefile: add install rule

bin/physlr-make
a variable to make it less painful calling our own installation of python
=> variable `python_executable`

src/physlr-molecules.cc
=> use std::max_element instead of manually updating maxVal

bin/physlr-make, physlr/physlr.py
Fly 
|Assembly|NG50|NGA50|# misassemblies|Genome fraction (%)|
| --- | --- | --- | --- |--- |
|Original|20,504,419|839,829|467|89.025|
|Edge intersection|18,548,285|720,198|329|77.852|
|Split minimizer based on graph|20,495,800|890,313|450|89.017|
|Split minimizer based on graph + orient with more pieces|20,495,800|968,954|473|88.988|
=> Use minimizers of each molecule rather than the barcode to map sequences

bin/physlr-make, physlr/physlr.py
To prime #141 , I have refactored physlr-map to avoid code duplication.
=> Refactor physlr-map

physlr/physlr.py
Correct pairs that are inconsistent with arcs pair
=> Arcs correction

.pylintrc, physlr/physlr.py
For certain stLFR datasets, even bi-connected components is too strict. I have added connected components which is a more lenient strategy.
=> connected components mol_strategy

bin/physlr-make, physlr/physlr.py
using `bfs`, include neighbours to a certain depth in the subgraph(s)
=> Physlr subgraph enable d

physlr/physlr.py
=> minor bug fix

README.md
* Update README.md
Co-authored-by: Lauren Coombe <lauren.e.coombe@gmail.com>
=> fix readme info (#181)

bin/physlr-make, physlr/hash.py, physlr/physlr.py
Using indexlr to feed long reads to Physlr
Added makefile lines to handle various technologies or data types (long/ont/pacbio - linked/10x/stlfr)
=> indexlr long reads
